macos_machine:
  - x86_64-apple-darwin13.4.0
  - arm64-apple-darwin20.0.0
MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.13            # [osx and x86_64]
cross_platform:
  - osx-64
  - osx-arm64
uname_machine:
  - x86_64
  - arm64
zip_keys:
  - - macos_machine
    - cross_platform
    - uname_machine
cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2017           # [win]
c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2017           # [win]
vc:
  - 14
c_compiler_version:     # [osx]
  - 11                  # [osx]
  - 12                  # [osx]
cxx_compiler_version:   # [osx]
  - 11                  # [osx]
  - 12                  # [osx]
