c_compiler:           # [osx]
  - clang_bootstrap   # [osx]
cxx_compiler:         # [osx]
  - clang_bootstrap   # [osx]

c_compiler_version:
  - 11.2.0            # [linux]
  - 17.0.6            # [osx]
cxx_compiler_version:
  - 11.2.0            # [linux]
  - 17.0.6            # [osx]

# We require SDK > 12
CONDA_BUILD_SYSROOT:
  # - /opt/MacOSX14.5.sdk # [osx and x86_64]
  # - /Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk # [osx and arm64]CONDA_BUILD_SYSROOT:
  - /opt/MacOSX13.3.sdk # [osx and x86_64]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk # [osx and arm64]