macos_machine:
  - x86_64-apple-darwin20.0.0    # [osx and x86_64]
  - arm64-apple-darwin20.0.0     # [osx and arm64]
  - x86_64-conda-linux-gnu       # [linux and x86_64]
  - s390x-conda-linux-gnu        # [linux and s390x]
  - aarch64-conda-linux-gnu      # [linux and aarch64]
  - powerpc64le-conda-linux-gnu  # [linux and ppc64le]
  - dummy  # [win]
cross_platform:
  - osx-64         # [osx and x86_64]
  - osx-arm64      # [osx and arm64]
  - linux-64       # [linux and x86_64]
  - linux-s390x    # [linux and s390x]
  - linux-aarch64  # [linux and aarch64]
  - linux-ppc64le  # [linux and ppc64le]
  - dummpy         # [win]
uname_machine:
  - x86_64       # [osx and x86_64]
  - arm64        # [osx and arm64]
  - x86_64       # [linux and x86_64]
  - s390x        # [linux and s390x]
  - aarch64      # [linux and aarch64]
  - powerpc64le  # [linux and ppc64le]
  - dummy        # [win]
zip_keys:
  - - macos_machine
    - cross_platform
    - uname_machine
cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2017           # [win]
c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2017           # [win]
vc:
  - 14
