macos_machine:
  - x86_64-apple-darwin13.4.0
  - arm64-apple-darwin20.0.0
MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.13            # [osx and x86_64]
cross_platform:
  - osx-64
  - osx-arm64
uname_machine:
  - x86_64
  - arm64

c_compiler:             # [osx]
  - clang_bootstrap     # [osx]
cxx_compiler:           # [osx]
  - clang_bootstrap     # [osx]
c_compiler_version:     # [osx]
  - "*"                 # [osx]
cxx_compiler_version:   # [osx]
  - "*"                 # [osx]

llvm_version:
  - 15.0
  - 16.0
  - 17.0

# zip it to avoid using rc-builds for already-released-in-conda-forge LLVM versions
channel_sources:
  - conda-forge
  - conda-forge
  - conda-forge/label/llvm_rc,conda-forge

channel_targets:
  - conda-forge main
  - conda-forge main
  - conda-forge llvm_rc

zip_keys:
  -
    - macos_machine
    - cross_platform
    - uname_machine
  -
    - llvm_version
    - channel_sources
    - channel_targets
