macos_machine:
  - x86_64-apple-darwin13.4.0  # [osx and x86_64]
  - arm64-apple-darwin20.0.0   # [osx and arm64]

vc:
  - 14

c_compiler_version:     # [osx]
  - 17                  # [osx]
cxx_compiler_version:   # [osx]
  - 17                  # [osx]