macos_machine:
  - x86_64-conda-linux-gnu       # [linux and x86_64]
  - aarch64-conda-linux-gnu      # [linux and aarch64]
cross_platform:
  - osx-64         # [osx and x86_64]
  - osx-arm64      # [osx and arm64]
  - linux-64       # [linux and x86_64]
  - linux-aarch64  # [linux and aarch64]
cxx_compiler:
  - clang_bootstrap  # [osx]
c_compiler:
  - clang_bootstrap  # [osx]