macos_machine:
  - x86_64-apple-darwin13.4.0
  - arm64-apple-macos11
cross_platform:
  - osx-64
  - osx-arm64
uname_machine:
  - x86_64
  - arm64
use_llvm_tools:
  - False
  - True
zip_keys:
  - - macos_machine
    - cross_platform
    - uname_machine
    - use_llvm_tools
cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2017           # [win]
c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2017           # [win]
vc:
  - 14
python:
  - 3.7
c_compiler_version:     # [osx]
  - "*"                 # [osx]
cxx_compiler_version:   # [osx]
  - "*"                 # [osx]
