macos_machine:
  - x86_64-apple-darwin13.4.0  # [osx and x86_64]
  - arm64-apple-darwin20.0.0   # [osx and arm64]
cross_platform:
  - osx-64     # [osx and x86_64]
  - osx-arm64  # [osx and arm64]
cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2017           # [win]
c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2017           # [win]
vc:
  - 14
c_compiler_version:     # [osx]
  - "*"                 # [osx]
cxx_compiler_version:   # [osx]
  - "*"                 # [osx]