{% set cctools_version = '927.0.2' %}
{% set ld64_version = '450.3' %}
{% set native_compiler_subdir = 'linux-64' %}  # [linux]

package:
  name: cctools-and-ld64
  version: {{ ld64_version }}

source:
  - url: https://github.com/tpoechtrager/cctools-port/archive/{{ cctools_version }}-ld64-{{ ld64_version }}.tar.gz
    sha256: 891981cb7c5490f4abdc32bf505d1b3151a7d64435a3aa36d3a0c296a34a8f64

build:
  number: 0
  skip: True  # [win]
  ignore_run_exports:
    - zlib

requirements:
  build:
    - clangxx  # [linux]
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - make
  host:
    #- xar
    # We only use the static library from this and only get away with that as it depends on nothing.
    - zlib
    - llvmdev
    - libuuid   # [linux]
    - tapi

outputs:
  - name: cctools
    version: {{ cctools_version }}
    script: install-cctools.sh
    build:
      activate_in_script: True
      ignore_run_exports:
        - zlib
    requirements:
      build:
        - {{ compiler('cxx') }}
        - autoconf
        - automake
        - make
      host:
        - zlib
        - llvmdev
        - tapi
        - libcxx  # [osx]
      run:
        - libcxx  # [osx]
    test:
      commands:
        - test -f $PREFIX/libexec/as/x86_64/as
        - test -f $PREFIX/bin/{{ macos_machine }}-as
        - test -f $PREFIX/bin/{{ macos_machine }}-ranlib
        - test -f $PREFIX/bin/{{ macos_machine }}-ar
        - test -f $PREFIX/bin/{{ macos_machine }}-otool
        - test -f $PREFIX/bin/{{ macos_machine }}-install_name_tool
        - test -f $PREFIX/bin/{{ macos_machine }}-strip
    about:
      home: https://opensource.apple.com/source
      license: APSL-2.0
      license_family: Other
      license_file: cctools/APPLE_LICENSE
      summary: Assembler, archiver, ranlib, libtool, otool et al for Darwin Mach-O files

  - name: ld64
    version: {{ ld64_version }}
    script: install-ld64.sh
    build:
      activate_in_script: True
      missing_dso_whitelist:
        - /usr/lib/libxar.1.dylib  # [osx]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - autoconf
        - automake
        - make
      host:
        - llvm
        - clang
        - tapi
        - libcxx  # [osx]
      run:
        - {{ pin_compatible("tapi") }}
        - libcxx  # [osx]
      run_constrained:
        - {{ pin_compatible("clang") }}
    test:
      commands:
        - test -f $PREFIX/bin/{{ macos_machine }}-ld
    about:
      home: https://opensource.apple.com/source
      license: APSL-2.0
      license_family: Other
      license_file: cctools/ld64/APPLE_LICENSE
      summary: Darwin Mach-O linker

extra:
  recipe-maintainers:
    - isuruf
    - mingwandroid
