{% set cctools_version = '986' %}
{% set ld64_version = '711' %}
{% set llvm_version = "17.0.6" %}

package:
  name: cctools-and-ld64
  version: {{ ld64_version }}

source:
  # latest commit from branch {{ cctools_version }}-ld64-{{ ld64_version }}
  - url: https://github.com/tpoechtrager/cctools-port/archive/437ced391dbf14dce86f977ca050a750d5682f39.tar.gz
    sha256: cf4020ddb92467de020c322eb13f0cac9ed992daa862a09bc2607e42467b3042
    patches:
      - patches/0001-Don-t-link-with-libc-abi.patch
      - patches/0002-ld64-add-conda-specific-env-vars-to-modify-lib-searc.patch
      # Taken from https://github.com/tpoechtrager/cctools-port/pull/116
      - patches/0003-Restore-using-__builtin_available-for-macos.patch
      # Taken from https://github.com/tpoechtrager/cctools-port/pull/118
      - patches/0004-Turn-off-outputIsMappableFile-when-building-to-osx-a.patch

build:
  number: 2
  skip: True  # [not osx]
requirements:
  build:
    - clangxx {{ llvm_version }}.*  # [linux]
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - llvmdev {{ llvm_version }}.*  # [build_platform != target_platform]
    - make
    - sed
    - patch

  host:
    #- xar
    # We only use the static library from this and only get away with that as it depends on nothing.
    - zlib
    - llvmdev {{ llvm_version }}
    - libuuid 1.41.5  # [linux]
    - libcxx-devel {{ llvm_version }}
    - tapi 1100.0.11

outputs:
  - name: ld64
    version: {{ ld64_version }}
    script: install-ld64.sh
    requirements:
      host:
        - llvm  {{ llvm_version }}
        - clang {{ llvm_version }}
        - libcxx-devel {{ llvm_version }}
        - tapi 1100.0.11
      run:
        - tapi
        - libcxx
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx]
      run_constrained:
        - {{ pin_compatible("clang") }}
        - ld {{ ld64_version }}.*
        - cctools {{ cctools_version }}.*
    test:
      commands:
        - test -f $PREFIX/bin/ld
    about:
      home: https://github.com/tpoechtrager/cctools-port
      license: APSL-2.0
      license_family: Other
      license_file: cctools/ld64/APPLE_LICENSE
      summary: Darwin Mach-O native linker
      description: |
        ld64 is Apple's linker for creating Mach-O executables and libraries.
        This native version provides:
        - Creation of Mach-O executables and dynamic libraries
        - Support for macOS-specific linking features
        - Generation of debug information compatible with macOS tools
        - Dynamic library versioning support

  - name: cctools
    version: {{ cctools_version }}
    script: install-cctools.sh
    requirements:
      host:
        - llvm  {{ llvm_version }}
        - clang {{ llvm_version }}
        - libcxx-devel {{ llvm_version }}
        - {{ pin_subpackage("ld64", exact=True) }}
      run:
        - {{ pin_subpackage("ld64", exact=True) }}
        - libcxx
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx]
      run_constrained:
        # clang might pull in the wrong cctools otherwise
        - clang {{ llvm_version }}.*
    test:
      commands:
        - test -f $PREFIX/bin/as
        - test -f $PREFIX/bin/ranlib
        - test -f $PREFIX/bin/ar
        - test -f $PREFIX/bin/otool
        - test -f $PREFIX/bin/install_name_tool
        - test -f $PREFIX/bin/strip
    about:
      home: https://github.com/tpoechtrager/cctools-port
      license: APSL-2.0
      license_family: Other
      license_file: cctools/APPLE_LICENSE
      summary: Native assembler, archiver, ranlib, libtool, otool et al for Darwin Mach-O files
      description: |
        This package provides native tools for working with macOS/Darwin binaries:
        - as: Assembler for macOS
        - ranlib: Archive index generator
        - ar: Archive manager for creating static libraries
        - otool: Object file examination tool similar to objdump
        - install_name_tool: Tool to modify dynamic shared library dependencies
        - strip: Tool to remove symbols from binaries

about:
  home: https://github.com/tpoechtrager/cctools-port
  dev_url: https://github.com/tpoechtrager/cctools-port
  doc_url: https://github.com/tpoechtrager/cctools-port
  license: APSL-2.0
  license_family: Other
  license_file: cctools/APPLE_LICENSE
  summary: Assembler, archiver, ranlib, libtool, otool et al for Darwin Mach-O files. Darwin Mach-O linker.
  description: |
    This package contains Apple's native toolchain components ported to other platforms:

    cctools - A collection of macOS/Darwin binary utilities including:
    - as: Assembler for converting assembly language to machine code
    - ar/ranlib: Archive management tools for static libraries
    - otool: Object file displaying tool (similar to objdump)
    - install_name_tool: Utility to manipulate dynamic shared library install names
    - strip: Tool to remove symbols and sections from binaries

    ld64 - The Darwin/macOS linker that creates:
    - Mach-O executables and libraries
    - Universal (fat) binaries for multiple architectures
    - Dynamic libraries with proper versioning

extra:
  recipe-maintainers:
    - isuruf
    - mingwandroid
    - davidbrochart
    - katietz
    - h-vetinari
  skip-lints:
    - should_use_compilers
    - missing_tests